apiVersion: v2
name: jenkins
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: jenkins/jenkins-operator
  version: 0.8.0
  repository: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart