apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: karpenter
    server: 
  project: default
  source:
    repoURL: 
    targetRevision: HEAD
    path: helm/karpenter-root
    helm:
      valuesObject:
        karpenter:
          serviceAccount:
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::something/something"
          settings:
            clusterName: "mycluster"
            interruptionQueue: "Karpenter-mycluster"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true