apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: default
spec:
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration
    - name: jenkins-casc-location
    #- name: jenkins-casc-ldap
    secret:
      name: jenkins-casc-ldap-secrets-admin
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "4423.vb_59f230b_ce53"
    - name: workflow-job
      version: "1571.vb_423c255d6d9"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "5.9.0"
    - name: job-dsl
      version: "1.93"
    - name: configuration-as-code
      version: "2037.v8e5349845172"
    - name: kubernetes-credentials-provider
      version: "1.301.v2eed6d439a_79"
    - name: nodejs
      version: "1.6.6"
    - name: ldap
      version: "807.v7d7de30930cf"
    - name: github-branch-source
      version: "1936.vfa_a_5c2cef4e7"
    - name: github
      version: "1.45.0"
    - name: pipeline-as-yaml
      version: "270.vc348a_45d9214"
    - name: matrix-auth
      version: "3.2.9"
    - name: github-oauth
      version: "685.v53b_070455063"
    - name: ssh-slaves
      version: "3.1096.v0b_cc466e4323"
    - name: docker-workflow
      version: "634.vedc7242b_eda_7"

    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.541.1-lts
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  1-system-message.yaml: |
    jenkins:
      systemMessage: "hello world"
      crumbIssuer:
          standard:
            excludeClientIPFromCrumb: true
      nodes:
        - permanent:
            labelString: "callisto quickring-dev yocto"
            launcher:
              ssh:
                credentialsId: "jenkins-ssh-dlockamy"
                host: "mars.softsurve.com"
                port: 22
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
            name: "mars"
            remoteFS: "/data/external/jenkins"
            retentionStrategy: "always"

    tool:
      nodejs:
        installations:
          - name: "NodeJS Latest"
            home: "" #required until nodejs-1.3.4 release (JENKINS-57508)
            properties:
              - installSource:
                  installers:
                    - nodeJSInstaller:
                        id: "12.11.1"
                        npmPackagesRefreshHours: 48 #default is 72
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-ldap
data:
  ldap.yaml: |
    jenkins:
      securityRealm:
        ldap:
          configurations:
            - displayNameAttributeName: "cn"
              groupMembershipStrategy:
                fromGroupSearch:
                  filter: "(member={0})"
              groupSearchBase: "ou=Users,o=5b873cfea0c12e71f6fff1d0,dc=jumpcloud,dc=com"
              groupSearchFilter: "(& (cn={0})(objectclass=groupOfNames))"
              inhibitInferRootDN: false
              managerDN: "uid=ldapservice,ou=Users,o=5b873cfea0c12e71f6fff1d0,dc=jumpcloud,dc=com"
              managerPasswordSecret: "${LDAP_MANAGER_PASSWORD}.password"
              server: "ldap://ldap.jumpcloud.com:389"
              userSearchBase: "ou=Users,o=5b873cfea0c12e71f6fff1d0,dc=jumpcloud,dc=com"
            disableMailAddressResolver: false
            disableRolePrefixing: true
            groupIdStrategy: "caseInsensitive"
            userIdStrategy: "caseInsensitive"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress-fairmece
  namespace: default
spec:
  ingressClassName: traefik # Specify your Ingress Controller class
  rules:
  - host: "jenkins.fairmerce.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-operator-http-example # The name of your Jenkins Service
            port:
              number: 8080 # The port the Jenkins Service exposes