apiVersion: v1
kind: Secret
metadata:
  name: "my-jenkins-credential-id"
  namespace: "default"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
    "jenkins.io/credentials-scope": "global"
  annotations:
    "jenkins.io/credentials-description": "A description of the credential"
type: Opaque
stringData:
  username: 'myuser'
  password: 'mypassword'
---
apiVersion: v1
kind: Secret
metadata:
  name: "jenkins-ldap-admin"
  namespace: "default"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
    "jenkins.io/credentials-scope": "global"
  annotations:
    "jenkins.io/credentials-description": "A description of the credential"
type: Opaque
stringData:
  username: 'uid=ldapservice,ou=Users,o=5b873cfea0c12e71f6fff1d0,dc=jumpcloud,dc=com'
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: "github-dlockamy-token"
  namespace: "default"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
    "jenkins.io/credentials-scope": "global"
  annotations:
    "jenkins.io/credentials-description": "A description of the credential"
type: Opaque
stringData:
  username: "dlockamy"
  password: ""
---